# Respuestas basadas en documentos oficiales JCE
DOCUMENT_RESPONSES = {
    "documento_ley_4-23": """📋 **Documento Oficial JCE**\n\n**Título:** Ley 4-23\n**Número:** No especificado\n**Fecha:** No especificada\n**Categoría:** Leyes\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_ley_285_04_migración": """📋 **Documento Oficial JCE**\n\n**Título:** Ley_285_04_Migración\n**Número:** 285\n**Fecha:** 27 de \nnoviembre de 1928\n**Categoría:** Leyes\n\n**Temas:** acta, nacimiento, cedula, identidad, junta central electoral\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_adendum_del_reglamento_para_la_validación_de_actas_del_estado_civil_y_cédulas": """📋 **Documento Oficial JCE**\n\n**Título:** ADENDUM DEL Reglamento para la Validación de Actas del Estado Civil y Cédulas\n**Número:** No especificado\n**Fecha:** No especificada\n**Categoría:** Reglamentos\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_paso_para_la_aplicacion_articulo_7-reglamento_vac-actualizado": """📋 **Documento Oficial JCE**\n\n**Título:** PASO PARA LA APLICACION ARTICULO 7-REGLAMENTO VAC-ACTUALIZADO\n**Número:** 02\n**Fecha:** 00/00/1945\n**Categoría:** Reglamentos\n\n**Artículos principales:**\n• Artículo 7: de Validación de Actas y Cédulas  \n \nSe adhiere Artículo 7 – Validación por Corrección Digital de Of...\n• Artículo 7: es: \nCorregir de oficio y de manera digital los datos  aquellos  Actos del Estado Civil \nque, en que...\n• Artículo 7: que se va a  aplicar....\n\n**Temas:** acta, nacimiento, cedula, matrimonio, registro civil\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_res._09-2007": """📋 **Documento Oficial JCE**\n\n**Título:** Res._09-2007\n**Número:** 275\n**Fecha:** 17 de julio \nde 1944\n**Categoría:** Resoluciones\n\n**Artículos principales:**\n• Artículo 31: de la precitada Ley 659 sobre Actos del Estado Civil, que establece, \nque cualquier persona puede pe...\n• Artículo 6: de la Ley No 659, que consignan que son \natribuciones del Oficial del Estado Civil, expedir copias d...\n• Artículo 30: de la Ley 659 sobre Actos del Estado Civil, que establece que el acta 31 \nserá firmada por el Oficia...\n\n**Temas:** acta, nacimiento, identidad, matrimonio, junta central electoral\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_resolucion_11-2021": """📋 **Documento Oficial JCE**\n\n**Título:** RESOLUCION 11-2021\n**Número:** 15\n**Fecha:** 17 de julio de 1944\n**Categoría:** Resoluciones\n\n**Temas:** acta, nacimiento, cedula, identidad, matrimonio\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_resolucion_005-2018": """📋 **Documento Oficial JCE**\n\n**Título:** RESOLUCION_005-2018\n**Número:** 05\n**Fecha:** 17 de julio de 1944\n**Categoría:** Resoluciones\n\n**Temas:** acta, nacimiento, cedula, identidad, matrimonio\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_circular_no._1-2024_sobre_las_notas_digitales_(1)": """📋 **Documento Oficial JCE**\n\n**Título:** CIRCULAR NO. 1-2024 SOBRE LAS NOTAS DIGITALES (1)\n**Número:** No especificado\n**Fecha:** No especificada\n**Categoría:** Circulares\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_manual_del_oficial_del_estado_civil": """📋 **Documento Oficial JCE**\n\n**Título:** Manual_del_Oficial_del_Estado_Civil\n**Número:** 659\n**Fecha:** 9/5/1995\n**Categoría:** Manuales\n\n**Artículos principales:**\n• Artículo 100: de la Ley No....\n\n**Temas:** acta, nacimiento, cedula, identidad, matrimonio\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_instruccion_renumeracion_actas_y_folios_corregido_(1)": """📋 **Documento Oficial JCE**\n\n**Título:** INSTRUCCION RENUMERACION ACTAS Y FOLIOS_CORREGIDO (1)\n**Número:** 02\n**Fecha:** 11/11/2022\n**Categoría:** Instrucciones\n\n**Temas:** acta, cedula, registro civil, junta central electoral, jce\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_mejoras_solicitud_de_servicios-flujo_gestion": """📋 **Documento Oficial JCE**\n\n**Título:** MEJORAS SOLICITUD DE SERVICIOS-FLUJO GESTION\n**Número:** No especificado\n**Fecha:** 06/11/2023\n**Categoría:** Otros\n\n**Temas:** acta, cedula, registro civil, tramite, tiempo\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
    "documento_solicitud_agilización_corrección_de_datos": """📋 **Documento Oficial JCE**\n\n**Título:** Solicitud Agilización Corrección de Datos\n**Número:** No especificado\n**Fecha:** No especificada\n**Categoría:** Otros\n\nℹ️ *Información basada en documentos oficiales de la JCE*""",
}
